package com.appndigital.amusepush

class Constants {

    companion object {
        //shared
        const val USER_PREFERENCES_KEY = "USER_PREFERENCES_KEY"
        const val FCM_TOKEN_PREFERENCES_KEY = "FCM_TOKEN_PREFERENCES_KEY"
        const val ADVERTISING_ID_CLIENT_PREFERENCES_KEY = "ADVERTISING_ID_CLIENT_PREFERENCES_KEY"
        const val DATE_INSTALL_PREFERENCES_KEY = "DATE_INSTALL_PREFERENCES_KEY"
        const val USER_ID_PREFERENCES_KEY = "USER_ID_PREFERENCES_KEY"
        const val TERMINAL_ID_PREF_KEY = "TERMINAL_ID_PREF_KEY"
        const val TOKEN_WEB_APP_PREF_KEY = "TOKEN_WEB_APP_PREF_KEY"
        const val LAST_DATE_OPENED_PREF_KEY = "LAST_DATE_OPENED_PREF_KEY"
    }
}